### PR TITLE
fix multiple logout call issue, added an easter egg

### LINKED ISSUE #60: Multiple logout calls
I noticed a very strange behavior. Clean state. Login from gui -> logout from gui -> everything ok. Login again -> logout again -> everything ok but I noticed that `/logout` endpoint was called 2 times at the same moment. Then I do login and logout again and this time `/logout` endpoint was called 3 times...and going on the times when `/logout` is called increase every time by 1. 

I replicated this behavior so it wasn't a one time case.

### PR DESCRIPTION
**Pull request by Eshaan7**
Closes #60.

### CODE REVIEW

File: src/app/pages/analyzers/analyzers-management/analyzers-management.component.ts [hunk 1]
```diff
@@ -2,6 +2,7 @@ import { Component } from '@angular/core';
 
 @Component({
   template: `
+    <!---- https://lotr.fandom.com/wiki/One_Ring -->
```
Comment (mlodic) [inline src/app/pages/analyzers/analyzers-management/analyzers-management.component.ts:5]: :heart:
